# see http://about.travis-ci.org/docs/user/languages/php/ for more hints

language: php
dist: trusty
sudo: required

php:
  - 7.0

before_script:
  - git clone https://github.com/eustasy/normal-checks.git
  - sudo apt-get install -y npm

script:
  - ./normal-checks/css.sh
  - ./normal-checks/javascript.sh
  - ./normal-checks/php.sh
  - php normal-checks/json.php
  - php normal-checks/xml.php

notifications:
  email:
    recipients:
      - lewisgoddard@eustasy.org
    on_success: change
    on_failure: always
